version: '3'
services:
  django:
    build:
      context: ./backend  # Path to your Django project directory
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
      - DATABASE_URL=mysql://your_db_user:your_db_password@mysql:3306/your_db_name
    volumes:
      - ./backend:/app  # Mount the Django project code into the container
    depends_on:
      - mysql  # Define the MySQL service as a dependency

  mysql:
    image: mysql:5.7  # Use a MySQL 5.7 container, you can choose a different version
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: your_root_password

  react:
    build:
      context: ./frontend  # Path to your React project directory
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    volumes:
      - ./frontend:/app  # Mount the React project code into the container
    depends_on:
      - django  # Define the Django service as a dependency
    environment:
      - REACT_APP_API_URL=http://django:8000  # Set the API URL for your React app
