# Generated by Django 4.2.6 on 2023-10-25 16:45

from django.db import migrations, models
import django.db.models.deletion
import rightmove.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
            ],
            bases=(models.Model, rightmove.models.TimeStampMixin),
        ),
        migrations.CreateModel(
            name='RightMoveProperty',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('bedrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('displayAddress', models.CharField(max_length=255)),
                ('propertySubType', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propertyUrl', models.URLField()),
                ('image', models.URLField()),
                ('firstVisibleDate', models.DateTimeField()),
                ('propertyTypeFullDescription', models.CharField(max_length=255)),
                ('addedOrReduced', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('branchDisplayName', models.CharField(max_length=255)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rightmove.area')),
            ],
            options={
                'db_table': 'rightmove_properties',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rightmove.rightmoveproperty')),
            ],
            options={
                'db_table': 'notes',
            },
            bases=(models.Model, rightmove.models.TimeStampMixin),
        ),
    ]
