# Generated by Django 4.2.6 on 2023-10-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0003_area_createdat_area_updatedat_note_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='rightmove.rightmoveproperty'),
        ),
    ]
