# Generated by Django 4.2.6 on 2023-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0004_alter_note_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightmoveproperty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
