# Generated by Django 4.2.6 on 2023-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0006_alter_note_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmoveproperty',
            name='property_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
