# Generated by Django 4.2.6 on 2023-10-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0007_alter_rightmoveproperty_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmoveproperty',
            name='property_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
