# Generated by Django 4.2.6 on 2023-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightmoveproperty',
            name='property_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rightmoveproperty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
