# Generated by Django 4.2.6 on 2023-10-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0005_rightmoveproperty_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rightmove.rightmoveproperty'),
        ),
    ]
